name: Devops_perfect
on:
  workflow_dispatch: null
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: basic command
        run: echo "i am perfect in basic commands"
  Docker:
    needs: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Docker expert
        run: echo "docker expert"
